language: python

python:
  - "2.7_with_system_site_packages"

install:
  - "wget -O - http://apt.mopidy.com/mopidy.gpg | sudo apt-key add -"
  - "sudo wget -O /etc/apt/sources.list.d/mopidy.list http://apt.mopidy.com/mopidy.list"
  - "sudo apt-get update || true"
  - "sudo apt-get install mopidy"
  - "pip install --allow-unverified=mopidy coveralls flake8 mopidy==dev"

script:
  - "flake8 $(find . -iname '*.py')"
  - "nosetests --with-coverage --cover-package=mopidy_{{ cookiecutter.ext_name }}"

after_success:
  - "coveralls"

{% if cookiecutter.github_username == 'mopidy' %}
notifications:
  irc:
    channels:
      - "irc.freenode.org#mopidy"
    on_success: change
    on_failure: change
    use_notice: true
    skip_join: true
{% endif %}
